namespace MicrosoftEntra.VerifiedId.Client.Models;

/// <summary>
/// An error response indicating a failure.
/// </summary>
public class ErrorResponse
{
    /// <summary>
    /// An autogenerated request ID.
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    /// The time of the error.
    /// </summary>
    public string? Date { get; set; }

    /// <summary>
    /// Internal Microsoft code.
    /// </summary>
    public string? Mscv { get; set; }

    /// <summary>
    /// The outer error object.
    /// </summary>
    public Error? Error { get; set; }
}