namespace MicrosoftEntra.VerifiedId.Client.Models;

/// <summary>
/// An error response indicating a failure.
/// </summary>
public class ErrorResponse
{
    /// <summary>
    /// An autogenerated request ID.
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    /// The time of the error.
    /// </summary>
    public string? Date { get; set; }

    /// <summary>
    /// Further details about the error.
    /// </summary>
    public ErrorDetail? Error { get; set; }
}