namespace MicrosoftEntra.VerifiedId.Client.Models;

/// <summary>
/// A response for an issuance request.
/// </summary>
public class IssuanceResponse
{
    /// <summary>
    /// An autogenerated correlation ID. The callback uses the same request, allowing you to keep track of the issuance request and its callbacks.
    /// </summary>
    public string? RequestId { get; set; }

    /// <summary>
    /// A URL that launches the authenticator app and starts the issuance process. You can present this URL to the user if they can't scan the QR code.
    /// </summary>
    public string? Url { get; set; }

    /// <summary>
    /// Indicates when the response will expire.
    /// </summary>
    public int Expiry { get; set; }

    /// <summary>
    /// A QR code that user can scan to start the issuance flow.
    /// </summary>
    public string? QRCode { get; set; }
}