name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    - name: Set variables
      run: |
        echo "AppVersion=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Build Containers
      run: |
        echo Building app version ${{ env.AppVersion }}
        docker build --no-cache --build-arg app_version=${{ env.AppVersion }} --build-arg source_version=$GITHUB_SHA -t jelledruyts/contosomusiversity:latest -f ./src/ContosoMusiversity/Dockerfile ./src
    - name: Push Containers to GitHub Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag jelledruyts/contosomusiversity:latest ghcr.io/jelledruyts/contosomusiversity:latest
        docker tag jelledruyts/contosomusiversity:${{ env.AppVersion }} ghcr.io/jelledruyts/contosomusiversity:${{ env.AppVersion }}
        docker push ghcr.io/jelledruyts/contosomusiversity:latest
        docker push ghcr.io/jelledruyts/contosomusiversity:${{ env.AppVersion }}
    - name: Azure Login
      uses: Azure/login@v1
      with:
        client-id: 'a619edb4-47c8-46bf-99f9-9ff26342c51a'
        tenant-id: '72f988bf-86f1-41af-91ab-2d7cd011db47'
        subscription-id: '1963f1ce-358f-4a5c-b5a8-c4931cdf49cf'
    - name: Update Container Apps
      uses: Azure/cli@v1
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp update -n containerapp-app-kontoso -g identitysamplesverifiedid -i jelledruyts/contosomusiversity:${{ env.AppVersion }} --registry-login-server ghcr.io --debug
